-- AlterTable
ALTER TABLE "Blog" ADD COLUMN     "ban" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "del" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "Admin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "ban" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "del" BOOLEAN NOT NULL DEFAULT false;
